# Site settings
title: goofmint.dev
description: >-
  Personal Portfolio Site of Atsushi Nakatsugawa, a DevRel lover based in Yokohama, Japan.
baseurl: ""
url: "https://goofmint.dev"

# Language settings
languages: ["ja", "en"]
default_lang: "ja"
lang: "ja"

# Author settings
author:
  name: Goofmint
  email: your-email@example.com

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  projects_en:
    output: true
    permalink: /en/projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      lang: "ja"
  - scope:
      path: ""
      type: "projects_en"
    values:
      layout: "project"
      lang: "en"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "ja"
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      permalink: /en/blog/:year/:month/:day/:title/
